[vertica]
host: <vertica-host>
port: 5433
user: <vertica-user>
password: <vertica-password>
database: <vertica-database>
schema: <vertica-schema>
ssl: False

parallel_num: 1
concurrency_num: 1
num_of_queries: 1
sleep_ms: 500

file_format: csv
column_separator: ,
max_filter_ratio: 0
timeout: 10000
